apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  apiUrl: "http://localhost:5000/api"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"

  # Origen desde donde el navegador accede al frontend
  Cors__AllowedOrigins__0: "http://localhost:4200"
  Cors__AllowedOrigins__1: "http://127.0.0.1:54835"
