apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4200        # puerto del servicio
      targetPort: 80  # puerto del contenedor
  type: NodePort